# -*- coding: utf-8 -*-
"""Model Analysis Lab Work

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cnuwI1gbgrxjo0IBc0yjgQArkZSrMzjx

Experiment 1 (study hours vs marks)
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import linear_model

X= [1,2,3,4,5]
Y= [2,4,5,4,5]
data = {'X': X, 'Y': Y}
df = pd.DataFrame(data)
print(df)
# %matplotlib inline
plt.scatter(df.X,df.Y,color='red',marker = '+')
plt.xlabel('Study Hours')
plt.ylabel('Marks')
reg = linear_model.LinearRegression()
reg.fit(df[['X']],df.Y)
plt.plot(df.X,reg.predict(df[['X']]))
print(reg.coef_)
print(reg.intercept_)

"""Experiment 2: Ad spend vs Sales"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import linear_model
X = [1,2,3,4,5]
Y = [2,3,5,5,8]
data = {'X':X,'Y':Y}
df = pd.DataFrame(data)
print(df)
# %matplotlib inline
plt.scatter(df.X,df.Y,color='red',marker = '+')
plt.xlabel('Ad Spend')
plt.ylabel('Sales')
reg = linear_model.LinearRegression()
reg.fit(df[['X']],df.Y)
print(reg.coef_)
print(reg.intercept_)
# %matplotlib inline
plt.scatter(df.X,df.Y,color='red',marker = '+')
plt.xlabel('Ad Spend')
plt.ylabel('Sales')
plt.plot(df.X,reg.predict(df[['X']]))

"""Experience vs Salary"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import linear_model
X = [1,2,2,4,5]
Y = [5,8,11,14,17]
data = {'X':X,'Y':Y}
df = pd.DataFrame(data)
print(df)
# %matplotlib inline
plt.scatter(df.X,df.Y,color='red',marker = '+')
plt.xlabel('Experience')
plt.ylabel('Salary')
reg = linear_model.LinearRegression()
reg.fit(df[['X']],df.Y)
print(reg.coef_)
print(reg.intercept_)
# %matplotlib inline
plt.scatter(df.X,df.Y,color='red',marker = '+')
plt.xlabel('Experience')
plt.ylabel('Salary')
plt.plot(df.X,reg.predict(df[['X']]))

"""Temperature vs Sales"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import linear_model
X = [2,4,6,8,10]
Y = [3,6,8,11,14]
data = {'X':X,'Y':Y}
df = pd.DataFrame(data)
print(df)
# %matplotlib inline
plt.scatter(df.X,df.Y,color='red',marker = '+')
plt.xlabel('Temperature')
plt.ylabel('Sales')
reg = linear_model.LinearRegression()
reg.fit(df[['X']],df.Y)
print(reg.coef_)
print(reg.intercept_)
# %matplotlib inline
plt.scatter(df.X,df.Y,color='red',marker = '+')
plt.xlabel('Temperature')
plt.ylabel('Sales')
plt.plot(df.X,reg.predict(df[['X']]))

"""Fertilizer vs Defects"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import linear_model
X = [1,2,3,4,5]
Y = [10,9,7,5,4]
data = {'X':X,'Y':Y}
df = pd.DataFrame(data)
print(df)
# %matplotlib inline
plt.scatter(df.X,df.Y,color='red',marker = '+')
plt.xlabel('Fertilizer')
plt.ylabel('Defects')
reg = linear_model.LinearRegression()
reg.fit(df[['X']],df.Y)
print(reg.coef_)
print(reg.intercept_)
# %matplotlib inline
plt.scatter(df.X,df.Y,color='red',marker = '+')
plt.xlabel('Fertilizer')
plt.ylabel('Defects')
plt.plot(df.X,reg.predict(df[['X']]))

"""Experiment 3: Multivariable Regression(Hour Studied vs Hour Slept)"""

x1 = np.array([1,2,1])
x2 = np.array([2,2,1])
y = np.array([6,9,4])
x = np.column_stack((np.ones(3),x1,x2))
B = np.linalg.inv(x.T @ x) @ x.T @ y
b0,b1,b2 = B
print("intercept",b0)
print("coefficient",b1)
print("coefficient of sleep hour ", b2)

"""Univariate Regression"""

x = np.array([1,2,3])
y = np.array([2,4,5])
X = np.column_stack((np.ones(3),x))
B = np.linalg.inv(X.T @ X) @ X.T @ y
b0,b1 = B
print("intercept",b0)
print("target",b1)

"""Experiment 04: District Outcome(Multivariate Regression)"""

x1 = np.array([1,2,3])
y1 = np.array([2,4,5])
y2 = np.array([10,20,25])
X = np.column_stack((np.ones(3),x1))
Y = np.column_stack((y1,y2))
B = np.linalg.inv(X.T @ X) @ X.T @ y
b0,b1 = B
print("intercept",b0)
print("intercept",b1)

"""Experiment 05: Polynomial Regression"""

x1 = np.array([1,2,3,4])
y = np.array([2,5,10,17])
X = np.column_stack((np.ones(4),x1,x1**2))
B = np.linalg.inv(X.T @ X) @ X.T @ y
b0,b1,b2 = B
print("intercept",b0)
print("coefficient of x ", b1)
print("coefficient of x**2",b2)

"""Experiment 06: Logistic Regression"""

import numpy as np
x1 = np.array([3,1,2,4,3])
x2 = np.array([6,3,4,7,5])
y = np.array([1,0,0,1,1])
X = np.column_stack((np.ones(5),x1,x2))
B = np.linalg.inv(X.T @ X) @ X.T @ y
b0,b1,b2 = B
print("intercept",b0)
print("coefiiecient for study hours",b1)
print("coefficient for sleep hours",b2)
import math
def sigmoid(x):
    return 1/(1+math.exp(-x))
Z = X@B
print("\n linear combination(Z)",Z)
Y_prob = np.array([sigmoid(val) for val in Z])
print("\n Predicted Probabilities (sigmoid outout)")
print(Y_prob)

Y_pred = (Y_prob >= 0.5).astype(int) # Convert probabilities to binary predictions

TP = np.sum((y==1)&(Y_pred==1))
TN = np.sum((y==0)&(Y_pred==0))
FP = np.sum((y==0)&(Y_pred==1))
FN = np.sum((y==1)&(Y_pred==0))
print("\n confusion matrix")
print(f"TP={TP},FP = {FP}")
print(f"FN= {FN}, TN = {TN}")
accuracy = (TP+TN)/(TP+TN+FP+FN) if (TP+TN+FP+FN) != 0 else 0
precision = TP/(TP+FP) if (TP+FP)!=0 else 0
recall = TP/(TP+FN) if (TP+FN)!=0 else 0
F1_score = 2* (precision * recall)/(precision + recall) if (precision + recall) != 0 else 0
print("\n Classification matrix")
print(f"Accuracy = {accuracy:.4f}")
print(f"Precision = {precision:.4f}")
print(f"Recall = {recall:.4f}")
print(f"F1_score = {F1_score:.4f}")

"""Experiment 07: Regression Regularization Technique"""

import numpy as np
import pandas as pd
from sklearn.linear_model import Lasso
from sklearn.model_selection import train_test_split
from sklearn.processing import standard scalar
from sklearn.metrics import mean_squared_error,r2_score
np.random.seed(42)
x= np.random.randn(100,5)
y= 3*x[:,1]-2*x[:,2]+np.random.randn(100)*0.5
x_train,x_text,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 42)
scalar = standard scalar()
x_train_scalar = scalar.fit_transformer(x_train)
Lasso.fit(x_train_scalar,y_train)
y_pred = Lasso.predict(x_test_scalar)
mse = mean_squared_error(y_test,y_pred)
r2 = r2_score(y_test,y_pred)
print(f"Mean Squared Error: {mse:.2f}")
print(f"R-squared: {r2:.2f}")
print("lasso coefficients:",LookupError)

"""Experiment 08: K-nearest Neighbour Classification"""

import math
from collections import Counter
points = ['A', 'B', 'C', 'D']
x1 = [7, 8, 5, 9]
x2 = [2, 1, 4, 6]
labels = ['pos', 'neg', 'pos', 'neg']
p = (8, 2)
k = 3
dataset = []
for i in range(len(points)):
    dist = math.sqrt((p[0] - x1[i])**2 + (p[1] - x2[i])**2)
    dataset.append({
        'name': points[i],
        'dist': dist,
        'label': labels[i]
    })
dataset.sort(key=lambda x: x['dist'])
neighbors = dataset[:k]
neighbor_labels = [n['label'] for n in neighbors]
pred = Counter(neighbor_labels).most_common(1)[0][0]
for n in neighbors:
    print(f"neighbour {n['name']}, distance: {n['dist']}, class: {n['label']}")
print("finally prediction for p :", pred)

"""Experiment 09: Naive Bayes Analysis"""

import pandas as pd
def naive_bayespredict(data,query):
    df =  pd.DataFrame(data)
    return None
dataset = {
    'Day': ['D1','D2','D3','D4','D5','D6','D7','D8','D9','D10','D11','D12','D13','D14'],
    'Outlook': ['sunny','sunny','overcast','rain','rain','rain','overcast','sunny','sunny','rain','sunny','overcast','overcast','rain'],
    'Temperature': ['hot','hot','hot','mild','cool','cool','mild','hot','cool','mild','mild','mild','hot','mild'],
    'Humidity': ['high','high','high','high','normal','normal','normal','high','normal','normal','normal','high','normal','high'],
    'Wind': ['weak','strong','weak','weak','weak','strong','strong','weak','weak','weak','strong','strong','weak','strong'],
    'Play Tennis': ['no','no','yes','yes','yes','no','yes','no','yes','yes','yes','yes','yes','no']
}
df = pd.DataFrame(dataset)
total_count = len(df)
class_counts = df['Play Tennis'].value_counts()
p_yes = class_counts['yes']/total_count
p_no = class_counts['no']/total_count
print(f"P(yes): {p_yes}")
print(f"P(no): {p_no}")
query = {'Outlook': 'sunny', 'Humidity': 'normal'}
posterior_yes = p_yes
posterior_no = p_no
print(f"\n---likelihoods---")
for feature, value in query.items():
    yes_subset = df[df['Play Tennis'] == 'yes']
    no_subset = df[df['Play Tennis'] == 'no']
    feature_counts_yes = (yes_subset[yes_subset[feature]==value].shape[0])/class_counts['yes']
    feature_counts_no = (no_subset[no_subset[feature]==value].shape[0])/class_counts['no']
    posterior_yes *= feature_counts_yes
    posterior_no *= feature_counts_no
    print(f"P({feature}={value}|yes): {feature_counts_yes:.4f}, P({feature}={value}|no): {feature_counts_no:.4f}")
print(f"\n---posterior scores---")
print(f"score(yes):{posterior_yes:.6f}")
print(f"score(no):{posterior_no:.6f}")
evidence = posterior_yes +posterior_no
Prob_yes = posterior_yes/evidence
Prob_no = posterior_no/evidence
print(f"\n--- posterior probabilities---")
print(f"probability of yes: {Prob_yes:.4f}")
print(f"probability of no: {Prob_no:.4f}")
prediction = 'yes' if Prob_yes > Prob_no else 'no'
new_instance = {
    'outlook': 'sunny',
    'temperature':'cool',
    'humidity':'high',
    'wind':'strong'
}
prediction = naive_bayespredict(dataset,new_instance)
print(f"\n Predicted class for new_instance (using incomplete function): {prediction}")
print(f"\n Predicted class for the query {{'Outlook': 'sunny', 'Humidity': 'normal'}}: {'yes' if Prob_yes > Prob_no else 'no'}")

"""Experiment 10: ROC - Curve"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve,auc
Probability_series = np.array([0.9,0.8,0.7,0.6,0.55,0.53,0.51,0.50])
classes = ['P','P','N','P','P','N','N','N','P','N']
y_true = np.array([1 if c=='P' else 0 for c in classes[:len(Probability_series)]])
fpr,tpr,thresholds = roc_curve(y_true,Probability_series)
roc_auc = auc(fpr,tpr)
plt.figure(figsize = (7,6))
plt.plot(fpr,tpr,color = 'blue',lw = 2, label = 'ROC curve(AUC = %0.3f)' % roc_auc)
plt.plot([0,1],[0,1],color = 'red',lw = 2, linestyle = '--',label = 'Random')
plt.xlim([0.0,1.0])
plt.ylim([0.0,1.05])
plt.ylabel('False positive rate(fpr)')
plt.xlabel('true positive rate(tpr)')
plt.title('(ROC curve) receiver operator characteristics')
plt.legend(loc = 'lower right')
plt.grid(True)
plt.show()
print("AUC value",roc_auc)